/// <reference path="Section3.ts" />

class USI9 extends USI9Section3 {
    constructor() {
        super();

        $('body').append('<div id="dialogPage"></div>');

        let self = this;

        $('#dialogPage').dialog({
            title: self._('help'),
            minHeight: 50,
            minWidth: 50,
            autoOpen: false
        });        
    }

    public renderSections() {
        document.addEventListener('pagerendered', (e: any) => {
            if (e.detail.pageNumber === 1) {
                this.renderSection1(
                    $('#dialogPage'),
                    $('[annotation-name=LastName]'),
                    $('[annotation-name=LastNameHelp]'),
                    $('[annotation-name=FirstName]'),
                    $('[annotation-name=FirstNameHelp]'),
                    $('[annotation-name=MiddleInitial]'),
                    $('[annotation-name=MiddleInitialHelp]'),
                    $('[annotation-name=OtherNames]'),
                    $('[annotation-name=OtherNamesHelp]'),
                    $('[annotation-name=Address]'),
                    $('[annotation-name=AddressHelp]'),
                    $('[annotation-name=ApartmentNumber]'),
                    $('[annotation-name=ApartmentNumberHelp]'),
                    $('[annotation-name=City]'),
                    $('[annotation-name=CityHelp]'),
                    $('[annotation-name=State]'),
                    $('[annotation-name=StateHelp]'),
                    $('[annotation-name=Zip]'),
                    $('[annotation-name=ZipHelp]'),
                    $('[annotation-name=DateOfBirth]'),
                    $('[annotation-name=DateOfBirthHelp]'),
                    $('[annotation-name=SSN11]'),
                    $('[annotation-name=SSN12]'),
                    $('[annotation-name=SSN13]'),
                    $('[annotation-name=SSN21]'),
                    $('[annotation-name=SSN22]'),
                    $('[annotation-name=SSN31]'),
                    $('[annotation-name=SSN32]'),
                    $('[annotation-name=SSN33]'),
                    $('[annotation-name=SSN34]'),
                    $('[annotation-name=SSNHelp]'),
                    $('[annotation-name=Email]'),
                    $('[annotation-name=EmailHelp]'),
                    $('[annotation-name=Phone]'),
                    $('[annotation-name=PhoneHelp]'),
                    $('[annotation-name=Citizen]'),
                    $('[annotation-name=CitizenHelp]'),
                    $('[annotation-name=NonCitizenNational]'),
                    $('[annotation-name=NonCitizenNationalHelp]'),
                    $('[annotation-name=LawfulPermanentResident]'),
                    $('[annotation-name=LawfulPermanentResidentHelp]'),
                    $('[annotation-name=AlienAuthorizedToWork]'),
                    $('[annotation-name=AlienAuthorizedToWorkHelp]'),
                    $('[annotation-name=USCISNumberHelp]'),
                    $('[annotation-name=LPRUSCISNumberPrefix]'),
                    $('[annotation-name=LPRUSCISNumber]'),
                    $('[annotation-name=LPRUSCISNumberType]'),
                    $('[annotation-name=AlienWorkAuthorizationDate]'),
                    $('[annotation-name=AlienUSCISNumberPrefix]'),
                    $('[annotation-name=AlienUSCISNumber]'),
                    $('[annotation-name=AlienUSCISNumberType]'),
                    $('[annotation-name=AdmissionNumber]'),
                    $('[annotation-name=AdmissionNumberHelp]'),
                    $('[annotation-name=ForeignPassportNumber]'),
                    $('[annotation-name=ForeignPassportNumberHelp]'),
                    $('[annotation-name=CountryOfIssuance]'),
                    $('[annotation-name=CountryOfIssuanceHelp]'),
                    $('[annotation-name=sgnEmployee]'),
                    $('[annotation-name=sgnEmployeeHelp]'),
                    $('[annotation-name=sgnEmployeeDate]'),
                    $('[annotation-name=sgnEmployeeDateHelp]')
                );
        
                this.renderTranslatorSection(
                    $('#dialogPage'),
                    $('[annotation-name=PreparerOrTranslatorNo]'),
                    $('[annotation-name=PreparerOrTranslatorYes]'),
                    $('[annotation-name=PreparerOrTranslatorHelp]'),
                    $('[annotation-name=sgnTranslator]'),
                    $('[annotation-name=sgnTranslatorHelp]'),
                    $('[annotation-name=TranslatorDate]'),
                    $('[annotation-name=TranslatorDateHelp]'),
                    $('[annotation-name=TranslatorLastName]'),
                    $('[annotation-name=TranslatorLastNameHelp]'),
                    $('[annotation-name=TranslatorFirstName]'),
                    $('[annotation-name=TranslatorFirstNameHelp]'),
                    $('[annotation-name=TranslatorAddress]'),
                    $('[annotation-name=TranslatorAddressHelp]'),
                    $('[annotation-name=TranslatorCity]'),
                    $('[annotation-name=TranslatorCityHelp]'),
                    $('[annotation-name=TranslatorState]'),
                    $('[annotation-name=TranslatorStateHelp]'),
                    $('[annotation-name=TranslatorZip]'),
                    $('[annotation-name=TranslatorZipHelp]')
                );
            }
        
            if (e.detail.pageNumber === 2) {
                this.renderSection2(
                    $('#dialogPage'),
                    $('[annotation-name=EmployeeInfoSection2Help]'),
                    $('[annotation-name=LastNameSection2]'),
                    $('[annotation-name=LastNameSection2Help]'),
                    $('[annotation-name=FirstNameSection2]'),
                    $('[annotation-name=FirstNameSection2Help]'),
                    $('[annotation-name=MiddleInitialSection2]'),
                    $('[annotation-name=MiddleInitialSection2Help]'),
                    $('[annotation-name=ImmigrationStatus]'),
                    $('[annotation-name=ImmigrationStatusHelp]'),
                    $('[annotation-name=ListADocTitle]'),
                    $('[annotation-name=ListADocTitleHelp]'),
                    $('[annotation-name=ListAIssuingAuthority]'),
                    $('[annotation-name=ListAIssuingAuthorityHelp]'),
                    $('[annotation-name=ListADocNumber]'),
                    $('[annotation-name=ListADocNumberHelp]'),
                    $('[annotation-name=ListAExpDate]'),
                    $('[annotation-name=ListAExpDateHelp]'),
                    $('[annotation-name=ListADocTitle2]'),
                    $('[annotation-name=ListADocTitle2Help]'),
                    $('[annotation-name=ListAIssuingAuthority2]'),
                    $('[annotation-name=ListAIssuingAuthority2Help]'),
                    $('[annotation-name=ListADocNumber2]'),
                    $('[annotation-name=ListADocNumber2Help]'),
                    $('[annotation-name=ListAExpDate2]'),
                    $('[annotation-name=ListAExpDate2Help]'),
                    $('[annotation-name=ListADocTitle3]'),
                    $('[annotation-name=ListADocTitle3Help]'),
                    $('[annotation-name=ListAIssuingAuthority3]'),
                    $('[annotation-name=ListAIssuingAuthority3Help]'),
                    $('[annotation-name=ListADocNumber3]'),
                    $('[annotation-name=ListADocNumber3Help]'),
                    $('[annotation-name=ListAExpDate3]'),
                    $('[annotation-name=ListAExpDate3Help]'),
                    $('[annotation-name=ListBDocTitle]'),
                    $('[annotation-name=ListBDocTitleHelp]'),
                    $('[annotation-name=ListBIssuingAuthority]'),
                    $('[annotation-name=ListBIssuingAuthorityHelp]'),
                    $('[annotation-name=ListBDocNumber]'),
                    $('[annotation-name=ListBDocNumberHelp]'),
                    $('[annotation-name=ListBExpDate]'),
                    $('[annotation-name=ListBExpDateHelp]'),
                    $('[annotation-name=ListCDocTitle]'),
                    $('[annotation-name=ListCDocTitleHelp]'),
                    $('[annotation-name=ListCIssuingAuthority]'),
                    $('[annotation-name=ListCIssuingAuthorityHelp]'),
                    $('[annotation-name=ListCDocNumber]'),
                    $('[annotation-name=ListCDocNumberHelp]'),
                    $('[annotation-name=ListCExpDate]'),
                    $('[annotation-name=ListCExpDateHelp]'),
                    $('[annotation-name=AdditionalInfo]'),
                    $('[annotation-name=AdditionalInfoHelp]'),
                    $('[annotation-name=HireDate]'),
                    $('[annotation-name=HireDateHelp]'),
                    $('[annotation-name=sgnEmployer]'),
                    $('[annotation-name=sgnEmployerHelp]'),
                    $('[annotation-name=EmployerSignDate]'),
                    $('[annotation-name=EmployerSignDateHelp]'),
                    $('[annotation-name=EmployerTitle]'),
                    $('[annotation-name=EmployerTitleHelp]'),
                    $('[annotation-name=EmployerLastName]'),
                    $('[annotation-name=EmployerLastNameHelp]'),
                    $('[annotation-name=EmployerFirstName]'),
                    $('[annotation-name=EmployerFirstNameHelp]'),
                    $('[annotation-name=EmployerName]'),
                    $('[annotation-name=EmployerNameHelp]'),
                    $('[annotation-name=EmployerAddress]'),
                    $('[annotation-name=EmployerAddressHelp]'),
                    $('[annotation-name=EmployerCity]'),
                    $('[annotation-name=EmployerCityHelp]'),
                    $('[annotation-name=EmployerState]'),
                    $('[annotation-name=EmployerStateHelp]'),
                    $('[annotation-name=EmployerZip]'),
                    $('[annotation-name=EmployerZipHelp]')
                );

                this.renderSection3(
                    $('#dialogPage'),
                    $('[annotation-name=NewLastName]'),
                    $('[annotation-name=NewLastNameHelp]'),
                    $('[annotation-name=NewFirstName]'),
                    $('[annotation-name=NewFirstNameHelp]'),
                    $('[annotation-name=NewMiddleInitial]'),
                    $('[annotation-name=NewMiddleInitialHelp]'),
                    $('[annotation-name=RehireDate]'),
                    $('[annotation-name=RehireDateHelp]'),
                    $('[annotation-name=DocTitleSec3]'),
                    $('[annotation-name=DocTitleSec3Help]'),
                    $('[annotation-name=DocNumberSec3]'),
                    $('[annotation-name=DocNumberSec3Help]'),
                    $('[annotation-name=ExpDateSec3]'),
                    $('[annotation-name=ExpDateSec3Help]'),
                    $('[annotation-name=sgnEmployerSec3]'),
                    $('[annotation-name=sgnEmployerSec3Help]'),
                    $('[annotation-name=EmployerSignDateSec3]'),
                    $('[annotation-name=EmployerSignDateSec3Help]'),
                    $('[annotation-name=EmployerNameSec3]'),
                    $('[annotation-name=EmployerNameSec3Help]')
                );
            }
        });
    }
}

var form = new USI9();
form.renderSections();